# test this file with
#   goreleaser release --config goreleaser.yml --clean --snapshot
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/jpillora/chisel/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - formats:
      - gz
    files:
      - none*
release:
  draft: false
  prerelease: false
changelog:
  disable: true
