name: CI
on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  test:
    name: Linux Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
      - name: Build
        run: go build -v -o /dev/null .
      - name: Test
        run: go test -v ./...

  linux_build:
    name: Linux Build (${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch:
          - amd64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
      - name: Cross build
        env:
          CGO_ENABLED: "0"
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
        run: go build -trimpath -v -o /tmp/chisel-linux-${{ matrix.goarch }} .

  # ================
  # RELEASE BINARIES (on push "v*" tag)
  # ================
  release_binaries:
    name: Release Binaries
    needs:
      - test
      - linux_build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOTOOLCHAIN: auto
        with:
          version: latest
          args: release --clean --config .github/goreleaser.yml
